language: java
jdk:
  - openjdk8

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.grad;e'

script: "./gradlew clean build"

notifications:
  email:
    recipients:
      - "times132@naver.com"